"""Conformance fixtures for reac_control.ksy.

Decodes a set of known-good REAC control records (the worked examples from the
protocol reference) with the ksc-generated parser and asserts both the decode and
the Roland DT1 inner-checksum invariant. CI regenerates the parser from the spec
(`ksc -t python`) before running this, so a spec change that breaks the layout fails
the build. The full-corpus check (every capture) lives elsewhere; these fixtures are
the public gate.
"""
import importlib

from kaitaistruct import KaitaiStream, BytesIO

rc = importlib.import_module("reac_control")  # generated by ksc -t python


def parse(h):
    return rc.ReacControl(KaitaiStream(BytesIO(bytes.fromhex(h.replace(" ", "")))))


# (record hex, box input CH, PARAM enum name, VALUE)
HEADAMP = [
    ("cdea 0403 0013 000200fe 0e f041 0a 000012 12 0101 20 00 01 5d f7", 0x20, "phantom_48v", 1),
    ("cdea 0403 0013 000200fe 0e f041 0a 000012 12 0101 00 00 00 7e f7", 0x00, "phantom_48v", 0),
    ("cdea 0403 0013 000200fe 0e f041 0a 000012 12 0101 02 02 05 75 f7", 0x02, "sens", 5),
    ("cdea 0403 0013 000200fe 0e f041 0a 000012 12 0101 2f 00 01 4e f7", 0x2f, "phantom_48v", 1),
    ("cdea 0403 0013 000200fe 0e f041 0a 000012 12 0101 00 01 01 7c f7", 0x00, "pad_minus20db", 1),
]
GRANT = "cdea 0403 0014 000200fe 0f f041 0a 000012 12 0100 06 00 01 00 78 f7"


def test_headamp_records():
    for h, ch, param, val in HEADAMP:
        r = parse(h)
        assert r.op == 0x0403
        assert r.command == rc.ReacControl.DtCommand.dt1_set
        assert r.tag == rc.ReacControl.RegPage.head_amp
        assert r.payload.ch == ch
        assert r.payload.param.name == param
        assert r.payload.value == val
        assert r.sysex_end == b"\xf7"


def test_join_grant():
    r = parse(GRANT)
    assert r.tag == rc.ReacControl.RegPage.join_grant
    assert r.payload.body == bytes.fromhex("06000100")


def test_inner_checksum_is_0x80():
    # Roland DT1 checksum: sum(TAG..CKSUM) mod 256 == 0x80 on every control record.
    for h in [x[0] for x in HEADAMP] + [GRANT]:
        b = bytes.fromhex(h.replace(" ", ""))
        oplen = int.from_bytes(b[4:6], "big")
        rec_len = oplen - 0x0d
        assert (sum(b[18:18 + rec_len]) & 0xff) == 0x80
